/* exports an array of prompts from which to select */

const prompts = [
    "superfragilisticexpealadocious",
    "urmommmmmmmy",
    "cancancanyoudothecancan",
    "california dreamin",
    "global warming is gonna kill us all",
    "everything is pointless in the end",
    "the sufficient passing of time makes all morals neutral",
    "if you're not having fun, you're doing it wrong",
    "cheesecake is the best food",
    "when you wish upon a star",
    "peter piper picked a pepper",
    "i don't much like the human species",
    "the universe is deterministic",
    "pseudorandom is redundant. nothing is truly random",
    "life is short, gotta make it count",
    "death is the salt of life",
    "dividing by zero leads to mathematical absurdities",
    "in chess the queen is the most powerful piece",
    "lasagna is a delicious dinner",
    "being poor sucks",
    "do you know the muffin man?",
    "people I want to meet: fish",
    "i have never caught a fish",
    "i can type really really fast",
    "people suck, yes people suck, yup",
    "My favorite passtime is to not be around people",
    "I have faith that we're all doomed",
    "Computers don't hurt you like people do",
    "I don't have close friends, and I am happy",
    "Being in nature makes me feel whole",
    "I like the people I like, and that's about it",
    "There's nothing like hiking a mountain",
    "Don't worry, the Earth will burn and flood",
    "One day everybody's gonna die",
    "Time doesn't hear when you ask it to wait",
    "When the stars look down on me, what do they see?",
    "All we are is dust in the wind",
    "everything we build crumbles to the ground",
    "i think I might need therapy",
    "Heaven makes even less sense than hell",
    "What was god doing before he created the first thing?",
    "if I don't laugh, then I'll cry",
    "sometimes it feels good to punch my pillow",
    "if we accept reality, we lose our sanity",
    "it feels like my sanity is hanging off a cliff",
    "it doesn't feel good to lose your independence",
    "I'm always down for a cheeseburger and shake",
    "frozen custard > ice cream",
    "i i i i work out",
    "Not everyone shows love the same way",
    "I like to care for people... from a distance"
];

export default prompts;